import { useState } from 'react';
import { ShieldCheck, ArrowLeft } from 'lucide-react';
import type { Store } from '../lib/types';
import { api, ApiError } from '../lib/api';
import type { Challenge } from '../lib/api';
import MemberForm from './MemberForm';
import Brand from './Brand';
import OtpPreview from './OtpPreview';
export default function Auth({store,onLogin}:{store:Store;onLogin:()=>Promise<void>}){
 const [mode,setMode]=useState<'login'|'register'|'otp'>('login');
 const [identity,setIdentity]=useState('');const [memberCode,setMemberCode]=useState('');const [needsCode,setNeedsCode]=useState(false);const [password,setPassword]=useState('');const [otp,setOtp]=useState('');const [challenge,setChallenge]=useState<Challenge|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 function begin(value:Challenge){setChallenge(value);setOtp('');setError('');setMode('otp');setPassword('');}
 function switchMode(next:'login'|'register'){setChallenge(null);setOtp('');setError('');setMode(next);}
 async function run(action:()=>Promise<void>){setBusy(true);setError('');try{await action();}catch(e){setError((e as Error).message);if(e instanceof ApiError&&e.requiresMemberCode)setNeedsCode(true);}finally{setBusy(false);}}
 return <div className="auth-layout"><aside className="auth-story"><div className="brand"><Brand/></div></aside><main className="auth-main"><div className={`auth-card ${mode==='register'?'wide':''}`}><div className="demo-note"><ShieldCheck size={18}/> {import.meta.env.DEV?'Backend local · SMS mô phỏng':'Xác thực tài khoản'}</div><h2>{mode==='login'?'Kính chào huynh đệ':mode==='register'?'Đăng ký sinh hoạt':challenge?.purpose==='registration'?'Xác thực đăng ký':'Xác thực đăng nhập'}</h2><p className="muted">{mode==='otp'?'Nhập mã được cấp riêng cho tài khoản hiển thị bên dưới.':mode==='register'?'Cung cấp thông tin để đăng ký sinh hoạt tại Đạo Tràng Phật Hào.':'Đăng nhập để xem hồ sơ và đăng ký tu học tại Đạo Tràng Phật Hào.'}</p>{mode!=='otp'&&<div className="tabs"><button disabled={busy} className={mode==='login'?'active':''} onClick={()=>switchMode('login')}>Đăng nhập</button><button disabled={busy} className={mode==='register'?'active':''} onClick={()=>switchMode('register')}>Đăng ký</button></div>}
 {mode==='register'?<MemberForm members={[]} requirements={store.requirements} registration onSave={async(member,password)=>begin(await api<Challenge>('/auth/register','POST',{member,password}))}/>:mode==='login'?<form onSubmit={e=>{e.preventDefault();void run(async()=>begin(await api<Challenge>('/auth/login','POST',{identity,memberCode,password})));}}>
 <label className="field">Số điện thoại / Mã huynh đệ<input required value={identity} onChange={e=>{setIdentity(e.target.value);setMemberCode('');setNeedsCode(false);setError('');}} placeholder="Nhập số điện thoại hoặc PH00001" autoComplete="username"/></label>
 {needsCode&&<><p className="shared-phone-note">SĐT này dùng cho nhiều tài khoản. Nhập mã thành viên cần đăng nhập để gửi đúng mã xác thực.</p><label className="field">Mã thành viên đăng nhập<input required value={memberCode} onChange={e=>setMemberCode(e.target.value)} placeholder="Ví dụ: PH00001" autoComplete="off"/></label></>}
 <label className="field">Mật khẩu<input type="password" required value={password} onChange={e=>setPassword(e.target.value)} placeholder="Nhập mật khẩu" autoComplete="current-password"/></label>{import.meta.env.DEV&&<p className="small muted">Tài khoản mẫu: <b>PH00001</b> (quản lý tổng), <b>PH00002</b> (quản lý lớp), <b>PH00003</b> (huynh đệ). Mật khẩu ban đầu: <b>PhatHao@123</b>.</p>}{error&&<p className="error" role="alert">{error}</p>}<button disabled={busy} className="button primary full">{busy?'Đang xử lý…':'Đăng nhập'}</button></form>:challenge&&<form onSubmit={e=>{e.preventDefault();void run(async()=>{await api('/auth/verify','POST',{...challenge,code:otp});await onLogin();});}}><OtpPreview challenge={challenge}/><label className="field">Mã xác thực cho {challenge.memberId}<input autoFocus inputMode="numeric" pattern="[0-9]{6}" maxLength={6} required className="otp-input" value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,''))}/></label>{error&&<p className="error" role="alert">{error}</p>}<button disabled={busy} className="button primary full">{busy?'Đang xác thực…':'Xác thực và tiếp tục'}</button><button disabled={busy} type="button" className="text-button" onClick={()=>void run(async()=>begin(await api<Challenge>('/auth/resend','POST',challenge)))}>Gửi lại mã xác thực</button><button disabled={busy} type="button" className="text-button" onClick={()=>switchMode('login')}><ArrowLeft size={16}/> Quay lại đăng nhập</button></form>}
 </div></main></div>;
}
