import { useEffect, useState } from 'react';
import { ShieldCheck, ArrowLeft } from 'lucide-react';
import type { Store } from '../lib/types';
import { api, ApiError } from '../lib/api';
import type { Challenge, AuthResult } from '../lib/api';
import MemberForm from './MemberForm';
import Brand from './Brand';
import OtpPreview from './OtpPreview';
export default function Auth({store,onLogin,smsPreview,googleEnabled}:{store:Store;onLogin:()=>Promise<void>;smsPreview:boolean;googleEnabled:boolean}){
 const [googleEmail,setGoogleEmail]=useState('');
 useEffect(()=>{const result=new URLSearchParams(window.location.search).get('google');if(!result)return;const messages:Record<string,string>={cancelled:'Huynh đệ đã hủy đăng nhập Google.',failed:'Không thể xác thực Google. Vui lòng thử lại.',unavailable:'Đăng nhập Google chưa được cấu hình.',inactive:'Tài khoản cần hoàn tất đăng ký trước.'};if(result==='link')void api<{email:string}>('/auth/google/pending').then(data=>setGoogleEmail(data.email)).catch(e=>setError((e as Error).message));else setError(messages[result]??'Không thể đăng nhập Google.');const url=new URL(window.location.href);url.searchParams.delete('google');window.history.replaceState(null,'',url.pathname+url.search+url.hash);},[]);
 const [mode,setMode]=useState<'login'|'register'|'otp'>('login');
 const [identity,setIdentity]=useState('');const [memberCode,setMemberCode]=useState('');const [needsCode,setNeedsCode]=useState(false);const [password,setPassword]=useState('');const [otp,setOtp]=useState('');const [challenge,setChallenge]=useState<Challenge|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 async function finish(value:AuthResult){if('id' in value)begin(value);else await onLogin();}
 function begin(value:Challenge){setChallenge(value);setOtp('');setError('');setMode('otp');setPassword('');}
 function switchMode(next:'login'|'register'){setChallenge(null);setOtp('');setError('');setGoogleEmail('');setPassword('');setMode(next);}
 async function run(action:()=>Promise<void>){setBusy(true);setError('');try{await action();}catch(e){setError((e as Error).message);if(e instanceof ApiError&&e.requiresMemberCode)setNeedsCode(true);}finally{setBusy(false);}}
 return <div className="auth-layout"><aside className="auth-story"><div className="brand"><Brand/></div></aside><main className="auth-main"><div className={`auth-card ${mode==='register'?'wide':''}`}><div className="demo-note"><ShieldCheck size={18}/> {smsPreview?'Thử nghiệm · SMS tạm tắt':'Tài khoản huynh đệ'}</div>{smsPreview&&<p className="sms-test-notice" role="status">Mã OTP sẽ hiển thị trên website. Chỉ dùng dữ liệu thử; SĐT chưa được xác minh qua SMS.</p>}<h2>{mode==='login'?'Kính chào huynh đệ':mode==='register'?'Đăng ký sinh hoạt':challenge?.purpose==='registration'?'Xác thực đăng ký':'Xác thực đăng nhập'}</h2><p className="muted">{mode==='otp'?'Nhập mã được cấp riêng cho tài khoản hiển thị bên dưới.':mode==='register'?'Cung cấp thông tin để đăng ký sinh hoạt tại Đạo Tràng Phật Hào.':'Đăng nhập để xem hồ sơ và đăng ký tu học tại Đạo Tràng Phật Hào.'}</p>{mode!=='otp'&&<div className="tabs"><button disabled={busy} className={mode==='login'?'active':''} onClick={()=>switchMode('login')}>Đăng nhập</button><button disabled={busy} className={mode==='register'?'active':''} onClick={()=>switchMode('register')}>Đăng ký</button></div>}
 {mode==='register'?<MemberForm members={[]} requirements={store.requirements} registration onSave={async(member,password)=>{await finish(await api<AuthResult>('/auth/register','POST',{member,password}));}}/>:mode==='login'?<>{googleEnabled&&<><button type="button" className="button google-button full" disabled={busy||!googleEnabled} onClick={()=>{setBusy(true);window.location.assign('/api/auth/google/start');}}><svg viewBox="0 0 48 48" width="20" height="20" aria-hidden="true"><path fill="#4285F4" d="M43.61 24.46c0-1.36-.12-2.66-.35-3.92H24v7.42h11a9.4 9.4 0 0 1-4.08 6.17v5.13h6.62c3.87-3.56 6.07-8.81 6.07-14.8Z"/><path fill="#34A853" d="M24 44c5.5 0 10.1-1.82 13.54-4.94l-6.62-5.13c-1.83 1.23-4.18 1.98-6.92 1.98-5.3 0-9.8-3.58-11.41-8.4H5.77v5.29A20 20 0 0 0 24 44Z"/><path fill="#FBBC05" d="M12.59 27.51a12 12 0 0 1 0-7.02V15.2H5.77a20 20 0 0 0 0 17.6l6.82-5.29Z"/><path fill="#EA4335" d="M24 12.09c3 0 5.68 1.03 7.8 3.05l5.85-5.85A19.58 19.58 0 0 0 24 4 20 20 0 0 0 5.77 15.2l6.82 5.29c1.61-4.82 6.11-8.4 11.41-8.4Z"/></svg>Đăng nhập bằng Google</button><div className="auth-divider"><span>{googleEmail?'Liên kết hồ sơ hiện có':'Hoặc đăng nhập bằng mật khẩu'}</span></div></>}{googleEmail?<form onSubmit={e=>{e.preventDefault();void run(async()=>{await api('/auth/google/link','POST',{password});await onLogin();});}}><p className="google-link-note">Google đã xác thực <strong>{googleEmail}</strong>. Nhập mật khẩu của hồ sơ có email này để liên kết lần đầu. Những lần sau huynh đệ chỉ cần chọn tài khoản Google.</p><label className="field">Mật khẩu hồ sơ hiện tại<input type="password" required minLength={8} maxLength={128} autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p className="error" role="alert">{error}</p>}<button disabled={busy} className="button primary full">{busy?'Đang liên kết…':'Liên kết và đăng nhập'}</button><p className="small muted google-hint">Chưa có hồ sơ? Chọn Đăng ký và sử dụng email trên. Đã có hồ sơ nhưng chưa thêm email? Đăng nhập bằng mật khẩu để cập nhật email trước.</p><button type="button" className="text-button" disabled={busy} onClick={()=>switchMode('login')}>Quay lại đăng nhập</button></form>:<form onSubmit={e=>{e.preventDefault();void run(async()=>finish(await api<AuthResult>('/auth/login','POST',{identity,memberCode,password})));}}>
 <label className="field">Email / Số điện thoại / Mã huynh đệ<input required value={identity} onChange={e=>{setIdentity(e.target.value);setMemberCode('');setNeedsCode(false);setError('');}} placeholder="Nhập email, số điện thoại hoặc PH00001" autoComplete="username"/></label>
 {needsCode&&<><p className="shared-phone-note">SĐT này dùng cho nhiều tài khoản. Nhập mã thành viên cần đăng nhập để chọn đúng tài khoản.</p><label className="field">Mã thành viên đăng nhập<input required value={memberCode} onChange={e=>setMemberCode(e.target.value)} placeholder="Ví dụ: PH00001" autoComplete="off"/></label></>}
 <label className="field">Mật khẩu<input type="password" required value={password} onChange={e=>setPassword(e.target.value)} placeholder="Nhập mật khẩu" autoComplete="current-password"/></label>{process.env.NODE_ENV === 'development'&&<p className="small muted">Tài khoản mẫu: <b>PH00001</b> (quản lý tổng), <b>PH00002</b> (quản lý lớp), <b>PH00003</b> (huynh đệ). Mật khẩu ban đầu: <b>PhatHao@123</b>.</p>}{error&&<p className="error" role="alert">{error}</p>}<button disabled={busy} className="button primary full">{busy?'Đang xử lý…':'Đăng nhập'}</button></form>}</>:challenge&&<form onSubmit={e=>{e.preventDefault();void run(async()=>{await api('/auth/verify','POST',{...challenge,code:otp});await onLogin();});}}><OtpPreview challenge={challenge}/><label className="field">Mã xác thực cho {challenge.memberId}<input autoFocus inputMode="numeric" pattern="[0-9]{6}" maxLength={6} required className="otp-input" value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,''))}/></label>{error&&<p className="error" role="alert">{error}</p>}<button disabled={busy} className="button primary full">{busy?'Đang xác thực…':'Xác thực và tiếp tục'}</button><button disabled={busy} type="button" className="text-button" onClick={()=>void run(async()=>begin(await api<Challenge>('/auth/resend','POST',challenge)))}>Gửi lại mã xác thực</button><button disabled={busy} type="button" className="text-button" onClick={()=>switchMode('login')}><ArrowLeft size={16}/> Quay lại đăng nhập</button></form>}
 </div></main></div>;
}
