import { useState } from 'react';
import { Upload, X } from 'lucide-react';
import type { Member, Requirements, Field, MemberGroup } from '../lib/types';
import { fieldLabels, groupLabels } from '../lib/types';
import { today } from '../lib/utils';
type Props={member?:Member;requirements:Requirements;members:Member[];onSave:(member:Omit<Member,'id'>,password?:string)=>void|Promise<void>;onCancel?:()=>void;registration?:boolean};
export default function MemberForm({member,requirements,onSave,onCancel,registration=false}:Props){
 const [form,setForm]=useState({name:member?.name??'',birthday:member?.birthday??'',phone:member?.phone??'',address:member?.address??'',area:member?.area??'TP. Hồ Chí Minh',referrer:member?.referrer??'',joined:member?.joined??today(),avatar:member?.avatar??'',password:'',group:member?.group??'congregation'});
 const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 const field=(key:Field,type='text')=><label className="field" key={key}>{fieldLabels[key]} {requirements[key]&&<span className="required">*</span>}<input type={type} required={requirements[key]} value={form[key]} autoComplete={key==='password'?'new-password':undefined} minLength={key==='password'?8:undefined} max={key==='birthday'?today():undefined} onChange={e=>setForm({...form,[key]:e.target.value})} placeholder={key==='referrer'?'Ví dụ: PH00001':key==='phone'?'09xxxxxxxx':undefined}/></label>;
 async function upload(file?:File){if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024){setError('Chọn ảnh JPG, PNG hoặc WebP tối đa 5 MB.');return;}setBusy(true);try{const bitmap=await createImageBitmap(file);const canvas=document.createElement('canvas');const ratio=Math.min(1,480/Math.max(bitmap.width,bitmap.height));canvas.width=bitmap.width*ratio;canvas.height=bitmap.height*ratio;canvas.getContext('2d')!.drawImage(bitmap,0,0,canvas.width,canvas.height);setForm(f=>({...f,avatar:canvas.toDataURL('image/webp',0.8)}));bitmap.close();setError('');}catch{setError('Không đọc được ảnh này. Vui lòng chọn ảnh khác.');}finally{setBusy(false);}}
 return <form onSubmit={async e=>{e.preventDefault();setError('');if(requirements.avatar&&!form.avatar)return setError('Vui lòng thêm ảnh đại diện.');if(form.phone&&!/^0[35789]\d{8}$/.test(form.phone))return setError('Số điện thoại Việt Nam cần có 10 chữ số.');if(form.referrer===member?.id)return setError('Không thể tự giới thiệu chính mình.');if(!form.name.trim()&&requirements.name)return setError('Vui lòng nhập họ tên.');const {password,...profile}=form;setBusy(true);try{await onSave({...profile,name:profile.name.trim()},password);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>
 <div className="upload-row"><div className="avatar large">{form.avatar?<img src={form.avatar} alt="Ảnh đại diện"/>:<Upload size={24}/>}</div><div><label className="button secondary upload-button">{busy?'Đang xử lý…':'Chọn ảnh đại diện'}<input aria-label="Chọn ảnh đại diện" type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>void upload(e.target.files?.[0])} disabled={busy}/></label><p className="small muted">JPG, PNG, WebP · Tối đa 5 MB {requirements.avatar?'· Bắt buộc':''}</p></div>{form.avatar&&<button type="button" className="icon-button" aria-label="Xóa ảnh" onClick={()=>setForm({...form,avatar:''})}><X size={16}/></button>}</div>
 <div className="form-grid"><label className="field">Chúng / Nhóm sinh hoạt {requirements.group&&<span className="required">*</span>}<select aria-label="Chúng / Nhóm sinh hoạt" value={form.group} onChange={e=>setForm({...form,group:e.target.value as MemberGroup})}>{Object.entries(groupLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>{field('name')}{field('birthday','date')}<div>{field('phone','tel')}<p className="small muted shared-phone-help">Có thể dùng SĐT của phụ huynh cho nhiều tài khoản.</p></div><label className="field">Khu vực<select value={form.area} onChange={e=>setForm({...form,area:e.target.value})}>{['TP. Hồ Chí Minh','Bình Dương','Đồng Nai','Long An','Khu vực khác'].map(x=><option key={x}>{x}</option>)}</select></label><div className="span-two">{field('address')}</div>{field('referrer')}{field('joined','date')}{registration&&<div className="span-two">{field('password','password')}<p className="small muted">Tối thiểu 8 ký tự. Mật khẩu được băm và lưu tại backend, không lưu trong trình duyệt.</p></div>}</div>
 {error&&<p role="alert" className="error">{error}</p>}<div className="form-actions">{onCancel&&<button type="button" className="button secondary" onClick={onCancel}>Hủy</button>}<button className="button primary" disabled={busy}>{registration?'Đăng ký sinh hoạt':'Lưu thông tin'}</button></div></form>;
}
